//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCshtml5WCF.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        private System.Nullable<int> NullableTest1Field;
        
        private System.Nullable<int> NullableTest2Field;
        
        private System.Nullable<System.DateTime> NullableTest3Field;
        
        private System.Nullable<System.DateTime> NullableTest4Field;
        
        private char CharValueField;
        
        private TestCshtml5WCF.ServiceReference2.ToDoImportance ImportanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCshtml5WCF.ServiceReference2.ArrayOfString TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> NullableTest1 {
            get {
                return this.NullableTest1Field;
            }
            set {
                if ((this.NullableTest1Field.Equals(value) != true)) {
                    this.NullableTest1Field = value;
                    this.RaisePropertyChanged("NullableTest1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> NullableTest2 {
            get {
                return this.NullableTest2Field;
            }
            set {
                if ((this.NullableTest2Field.Equals(value) != true)) {
                    this.NullableTest2Field = value;
                    this.RaisePropertyChanged("NullableTest2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> NullableTest3 {
            get {
                return this.NullableTest3Field;
            }
            set {
                if ((this.NullableTest3Field.Equals(value) != true)) {
                    this.NullableTest3Field = value;
                    this.RaisePropertyChanged("NullableTest3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> NullableTest4 {
            get {
                return this.NullableTest4Field;
            }
            set {
                if ((this.NullableTest4Field.Equals(value) != true)) {
                    this.NullableTest4Field = value;
                    this.RaisePropertyChanged("NullableTest4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public char CharValue {
            get {
                return this.CharValueField;
            }
            set {
                if ((this.CharValueField.Equals(value) != true)) {
                    this.CharValueField = value;
                    this.RaisePropertyChanged("CharValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public TestCshtml5WCF.ServiceReference2.ToDoImportance Importance {
            get {
                return this.ImportanceField;
            }
            set {
                if ((this.ImportanceField.Equals(value) != true)) {
                    this.ImportanceField = value;
                    this.RaisePropertyChanged("Importance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public TestCshtml5WCF.ServiceReference2.ArrayOfString Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoImportance", Namespace="http://tempuri.org/")]
    public enum ToDoImportance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since element name GetToDosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        TestCshtml5WCF.ServiceReference2.GetToDosResponse GetToDos(TestCshtml5WCF.ServiceReference2.GetToDosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.GetToDosResponse> GetToDosAsync(TestCshtml5WCF.ServiceReference2.GetToDosRequest request);
        
        // CODEGEN: Generating message contract since element name toDoItem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponse AddOrUpdateToDo(TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponse> AddOrUpdateToDoAsync(TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest request);
        
        // CODEGEN: Generating message contract since element name toDoItemToReplace from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReplaceToDo", ReplyAction="http://tempuri.org/IService1/ReplaceToDoResponse")]
        TestCshtml5WCF.ServiceReference2.ReplaceToDoResponse ReplaceToDo(TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReplaceToDo", ReplyAction="http://tempuri.org/IService1/ReplaceToDoResponse")]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.ReplaceToDoResponse> ReplaceToDoAsync(TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest request);
        
        // CODEGEN: Generating message contract since element name toDoItem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        TestCshtml5WCF.ServiceReference2.DeleteToDoResponse DeleteToDo(TestCshtml5WCF.ServiceReference2.DeleteToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.DeleteToDoResponse> DeleteToDoAsync(TestCshtml5WCF.ServiceReference2.DeleteToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllToDos", ReplyAction="http://tempuri.org/IService1/DeleteAllToDosResponse")]
        void DeleteAllToDos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllToDos", ReplyAction="http://tempuri.org/IService1/DeleteAllToDosResponse")]
        System.Threading.Tasks.Task DeleteAllToDosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDos", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosResponse")]
        int GetTheNumberOfToDos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDos", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosResponse")]
        System.Threading.Tasks.Task<int> GetTheNumberOfToDosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDosPlusX", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosPlusXResponse")]
        System.Nullable<int> GetTheNumberOfToDosPlusX(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDosPlusX", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosPlusXResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> GetTheNumberOfToDosPlusXAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServerDate", ReplyAction="http://tempuri.org/IService1/GetServerDateResponse")]
        System.DateTime GetServerDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServerDate", ReplyAction="http://tempuri.org/IService1/GetServerDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetServerDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplyThreeNumbers", ReplyAction="http://tempuri.org/IService1/MultiplyThreeNumbersResponse")]
        double MultiplyThreeNumbers(double x1, double x2, double x3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplyThreeNumbers", ReplyAction="http://tempuri.org/IService1/MultiplyThreeNumbersResponse")]
        System.Threading.Tasks.Task<double> MultiplyThreeNumbersAsync(double x1, double x2, double x3);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDos", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.GetToDosRequestBody Body;
        
        public GetToDosRequest() {
        }
        
        public GetToDosRequest(TestCshtml5WCF.ServiceReference2.GetToDosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetToDosRequestBody {
        
        public GetToDosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDosResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.GetToDosResponseBody Body;
        
        public GetToDosResponse() {
        }
        
        public GetToDosResponse(TestCshtml5WCF.ServiceReference2.GetToDosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToDosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference2.ToDoItem[] GetToDosResult;
        
        public GetToDosResponseBody() {
        }
        
        public GetToDosResponseBody(TestCshtml5WCF.ServiceReference2.ToDoItem[] GetToDosResult) {
            this.GetToDosResult = GetToDosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDo", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequestBody Body;
        
        public AddOrUpdateToDoRequest() {
        }
        
        public AddOrUpdateToDoRequest(TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrUpdateToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem;
        
        public AddOrUpdateToDoRequestBody() {
        }
        
        public AddOrUpdateToDoRequestBody(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem) {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponseBody Body;
        
        public AddOrUpdateToDoResponse() {
        }
        
        public AddOrUpdateToDoResponse(TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddOrUpdateToDoResponseBody {
        
        public AddOrUpdateToDoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplaceToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReplaceToDo", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.ReplaceToDoRequestBody Body;
        
        public ReplaceToDoRequest() {
        }
        
        public ReplaceToDoRequest(TestCshtml5WCF.ServiceReference2.ReplaceToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplaceToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference2.ToDoItem toDoItemToReplace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TestCshtml5WCF.ServiceReference2.ToDoItem newToDo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool throwFaultExceptionIfNotFound;
        
        public ReplaceToDoRequestBody() {
        }
        
        public ReplaceToDoRequestBody(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            this.toDoItemToReplace = toDoItemToReplace;
            this.newToDo = newToDo;
            this.throwFaultExceptionIfNotFound = throwFaultExceptionIfNotFound;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplaceToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReplaceToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.ReplaceToDoResponseBody Body;
        
        public ReplaceToDoResponse() {
        }
        
        public ReplaceToDoResponse(TestCshtml5WCF.ServiceReference2.ReplaceToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplaceToDoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReplaceToDoResult;
        
        public ReplaceToDoResponseBody() {
        }
        
        public ReplaceToDoResponseBody(bool ReplaceToDoResult) {
            this.ReplaceToDoResult = ReplaceToDoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDo", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.DeleteToDoRequestBody Body;
        
        public DeleteToDoRequest() {
        }
        
        public DeleteToDoRequest(TestCshtml5WCF.ServiceReference2.DeleteToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem;
        
        public DeleteToDoRequestBody() {
        }
        
        public DeleteToDoRequestBody(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem) {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference2.DeleteToDoResponseBody Body;
        
        public DeleteToDoResponse() {
        }
        
        public DeleteToDoResponse(TestCshtml5WCF.ServiceReference2.DeleteToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteToDoResponseBody {
        
        public DeleteToDoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestCshtml5WCF.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestCshtml5WCF.ServiceReference2.IService1>, TestCshtml5WCF.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference2.GetToDosResponse TestCshtml5WCF.ServiceReference2.IService1.GetToDos(TestCshtml5WCF.ServiceReference2.GetToDosRequest request) {
            return base.Channel.GetToDos(request);
        }
        
        public TestCshtml5WCF.ServiceReference2.ToDoItem[] GetToDos() {
            TestCshtml5WCF.ServiceReference2.GetToDosRequest inValue = new TestCshtml5WCF.ServiceReference2.GetToDosRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.GetToDosRequestBody();
            TestCshtml5WCF.ServiceReference2.GetToDosResponse retVal = ((TestCshtml5WCF.ServiceReference2.IService1)(this)).GetToDos(inValue);
            return retVal.Body.GetToDosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.GetToDosResponse> TestCshtml5WCF.ServiceReference2.IService1.GetToDosAsync(TestCshtml5WCF.ServiceReference2.GetToDosRequest request) {
            return base.Channel.GetToDosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.GetToDosResponse> GetToDosAsync() {
            TestCshtml5WCF.ServiceReference2.GetToDosRequest inValue = new TestCshtml5WCF.ServiceReference2.GetToDosRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.GetToDosRequestBody();
            return ((TestCshtml5WCF.ServiceReference2.IService1)(this)).GetToDosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponse TestCshtml5WCF.ServiceReference2.IService1.AddOrUpdateToDo(TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest request) {
            return base.Channel.AddOrUpdateToDo(request);
        }
        
        public void AddOrUpdateToDo(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem) {
            TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest inValue = new TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponse retVal = ((TestCshtml5WCF.ServiceReference2.IService1)(this)).AddOrUpdateToDo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponse> TestCshtml5WCF.ServiceReference2.IService1.AddOrUpdateToDoAsync(TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest request) {
            return base.Channel.AddOrUpdateToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoResponse> AddOrUpdateToDoAsync(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem) {
            TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest inValue = new TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((TestCshtml5WCF.ServiceReference2.IService1)(this)).AddOrUpdateToDoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference2.ReplaceToDoResponse TestCshtml5WCF.ServiceReference2.IService1.ReplaceToDo(TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest request) {
            return base.Channel.ReplaceToDo(request);
        }
        
        public bool ReplaceToDo(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest inValue = new TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.ReplaceToDoRequestBody();
            inValue.Body.toDoItemToReplace = toDoItemToReplace;
            inValue.Body.newToDo = newToDo;
            inValue.Body.throwFaultExceptionIfNotFound = throwFaultExceptionIfNotFound;
            TestCshtml5WCF.ServiceReference2.ReplaceToDoResponse retVal = ((TestCshtml5WCF.ServiceReference2.IService1)(this)).ReplaceToDo(inValue);
            return retVal.Body.ReplaceToDoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.ReplaceToDoResponse> TestCshtml5WCF.ServiceReference2.IService1.ReplaceToDoAsync(TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest request) {
            return base.Channel.ReplaceToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.ReplaceToDoResponse> ReplaceToDoAsync(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest inValue = new TestCshtml5WCF.ServiceReference2.ReplaceToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.ReplaceToDoRequestBody();
            inValue.Body.toDoItemToReplace = toDoItemToReplace;
            inValue.Body.newToDo = newToDo;
            inValue.Body.throwFaultExceptionIfNotFound = throwFaultExceptionIfNotFound;
            return ((TestCshtml5WCF.ServiceReference2.IService1)(this)).ReplaceToDoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference2.DeleteToDoResponse TestCshtml5WCF.ServiceReference2.IService1.DeleteToDo(TestCshtml5WCF.ServiceReference2.DeleteToDoRequest request) {
            return base.Channel.DeleteToDo(request);
        }
        
        public void DeleteToDo(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem) {
            TestCshtml5WCF.ServiceReference2.DeleteToDoRequest inValue = new TestCshtml5WCF.ServiceReference2.DeleteToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            TestCshtml5WCF.ServiceReference2.DeleteToDoResponse retVal = ((TestCshtml5WCF.ServiceReference2.IService1)(this)).DeleteToDo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.DeleteToDoResponse> TestCshtml5WCF.ServiceReference2.IService1.DeleteToDoAsync(TestCshtml5WCF.ServiceReference2.DeleteToDoRequest request) {
            return base.Channel.DeleteToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestCshtml5WCF.ServiceReference2.DeleteToDoResponse> DeleteToDoAsync(TestCshtml5WCF.ServiceReference2.ToDoItem toDoItem) {
            TestCshtml5WCF.ServiceReference2.DeleteToDoRequest inValue = new TestCshtml5WCF.ServiceReference2.DeleteToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference2.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((TestCshtml5WCF.ServiceReference2.IService1)(this)).DeleteToDoAsync(inValue);
        }
        
        public void DeleteAllToDos() {
            base.Channel.DeleteAllToDos();
        }
        
        public System.Threading.Tasks.Task DeleteAllToDosAsync() {
            return base.Channel.DeleteAllToDosAsync();
        }
        
        public int GetTheNumberOfToDos() {
            return base.Channel.GetTheNumberOfToDos();
        }
        
        public System.Threading.Tasks.Task<int> GetTheNumberOfToDosAsync() {
            return base.Channel.GetTheNumberOfToDosAsync();
        }
        
        public System.Nullable<int> GetTheNumberOfToDosPlusX(int x) {
            return base.Channel.GetTheNumberOfToDosPlusX(x);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> GetTheNumberOfToDosPlusXAsync(int x) {
            return base.Channel.GetTheNumberOfToDosPlusXAsync(x);
        }
        
        public System.DateTime GetServerDate() {
            return base.Channel.GetServerDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetServerDateAsync() {
            return base.Channel.GetServerDateAsync();
        }
        
        public double MultiplyThreeNumbers(double x1, double x2, double x3) {
            return base.Channel.MultiplyThreeNumbers(x1, x2, x3);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyThreeNumbersAsync(double x1, double x2, double x3) {
            return base.Channel.MultiplyThreeNumbersAsync(x1, x2, x3);
        }
    }
}
