//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char CharValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference2.ToDoImportance ImportanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NullableTest1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NullableTest2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NullableTest3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NullableTest4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char CharValue {
            get {
                return this.CharValueField;
            }
            set {
                if ((this.CharValueField.Equals(value) != true)) {
                    this.CharValueField = value;
                    this.RaisePropertyChanged("CharValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference2.ToDoImportance Importance {
            get {
                return this.ImportanceField;
            }
            set {
                if ((this.ImportanceField.Equals(value) != true)) {
                    this.ImportanceField = value;
                    this.RaisePropertyChanged("Importance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NullableTest1 {
            get {
                return this.NullableTest1Field;
            }
            set {
                if ((this.NullableTest1Field.Equals(value) != true)) {
                    this.NullableTest1Field = value;
                    this.RaisePropertyChanged("NullableTest1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NullableTest2 {
            get {
                return this.NullableTest2Field;
            }
            set {
                if ((this.NullableTest2Field.Equals(value) != true)) {
                    this.NullableTest2Field = value;
                    this.RaisePropertyChanged("NullableTest2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NullableTest3 {
            get {
                return this.NullableTest3Field;
            }
            set {
                if ((this.NullableTest3Field.Equals(value) != true)) {
                    this.NullableTest3Field = value;
                    this.RaisePropertyChanged("NullableTest3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NullableTest4 {
            get {
                return this.NullableTest4Field;
            }
            set {
                if ((this.NullableTest4Field.Equals(value) != true)) {
                    this.NullableTest4Field = value;
                    this.RaisePropertyChanged("NullableTest4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoImportance", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public enum ToDoImportance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        WpfApplication1.ServiceReference2.ToDoItem[] GetToDos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        System.IAsyncResult BeginGetToDos(System.AsyncCallback callback, object asyncState);
        
        WpfApplication1.ServiceReference2.ToDoItem[] EndGetToDos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        void AddOrUpdateToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        System.IAsyncResult BeginAddOrUpdateToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem, System.AsyncCallback callback, object asyncState);
        
        void EndAddOrUpdateToDo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReplaceToDo", ReplyAction="http://tempuri.org/IService1/ReplaceToDoResponse")]
        bool ReplaceToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace, WpfApplication1.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ReplaceToDo", ReplyAction="http://tempuri.org/IService1/ReplaceToDoResponse")]
        System.IAsyncResult BeginReplaceToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace, WpfApplication1.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound, System.AsyncCallback callback, object asyncState);
        
        bool EndReplaceToDo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        void DeleteToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        System.IAsyncResult BeginDeleteToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteToDo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllToDos", ReplyAction="http://tempuri.org/IService1/DeleteAllToDosResponse")]
        void DeleteAllToDos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteAllToDos", ReplyAction="http://tempuri.org/IService1/DeleteAllToDosResponse")]
        System.IAsyncResult BeginDeleteAllToDos(System.AsyncCallback callback, object asyncState);
        
        void EndDeleteAllToDos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDos", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosResponse")]
        int GetTheNumberOfToDos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTheNumberOfToDos", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosResponse")]
        System.IAsyncResult BeginGetTheNumberOfToDos(System.AsyncCallback callback, object asyncState);
        
        int EndGetTheNumberOfToDos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDosPlusX", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosPlusXResponse")]
        System.Nullable<int> GetTheNumberOfToDosPlusX(int x);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTheNumberOfToDosPlusX", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosPlusXResponse")]
        System.IAsyncResult BeginGetTheNumberOfToDosPlusX(int x, System.AsyncCallback callback, object asyncState);
        
        System.Nullable<int> EndGetTheNumberOfToDosPlusX(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServerDate", ReplyAction="http://tempuri.org/IService1/GetServerDateResponse")]
        System.DateTime GetServerDate();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetServerDate", ReplyAction="http://tempuri.org/IService1/GetServerDateResponse")]
        System.IAsyncResult BeginGetServerDate(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndGetServerDate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplyThreeNumbers", ReplyAction="http://tempuri.org/IService1/MultiplyThreeNumbersResponse")]
        double MultiplyThreeNumbers(double x1, double x2, double x3);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/MultiplyThreeNumbers", ReplyAction="http://tempuri.org/IService1/MultiplyThreeNumbersResponse")]
        System.IAsyncResult BeginMultiplyThreeNumbers(double x1, double x2, double x3, System.AsyncCallback callback, object asyncState);
        
        double EndMultiplyThreeNumbers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoundTripTest", ReplyAction="http://tempuri.org/IService1/RoundTripTestResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication1.ServiceReference2.ToDoItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication1.ServiceReference2.ToDoImportance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication1.ServiceReference2.ToDoItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object RoundTripTest(object obj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RoundTripTest", ReplyAction="http://tempuri.org/IService1/RoundTripTestResponse")]
        System.IAsyncResult BeginRoundTripTest(object obj, System.AsyncCallback callback, object asyncState);
        
        object EndRoundTripTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoundTripTest2", ReplyAction="http://tempuri.org/IService1/RoundTripTest2Response")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication1.ServiceReference2.ToDoItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication1.ServiceReference2.ToDoImportance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WpfApplication1.ServiceReference2.ToDoItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object RoundTripTest2(object obj);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RoundTripTest2", ReplyAction="http://tempuri.org/IService1/RoundTripTest2Response")]
        System.IAsyncResult BeginRoundTripTest2(object obj, System.AsyncCallback callback, object asyncState);
        
        object EndRoundTripTest2(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReceiveFaultException", ReplyAction="http://tempuri.org/IService1/ReceiveFaultExceptionResponse")]
        bool ReceiveFaultException();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ReceiveFaultException", ReplyAction="http://tempuri.org/IService1/ReceiveFaultExceptionResponse")]
        System.IAsyncResult BeginReceiveFaultException(System.AsyncCallback callback, object asyncState);
        
        bool EndReceiveFaultException(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReceiveServerInternalErrorException", ReplyAction="http://tempuri.org/IService1/ReceiveServerInternalErrorExceptionResponse")]
        bool ReceiveServerInternalErrorException();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ReceiveServerInternalErrorException", ReplyAction="http://tempuri.org/IService1/ReceiveServerInternalErrorExceptionResponse")]
        System.IAsyncResult BeginReceiveServerInternalErrorException(System.AsyncCallback callback, object asyncState);
        
        bool EndReceiveServerInternalErrorException(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApplication1.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetToDosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetToDosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WpfApplication1.ServiceReference2.ToDoItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WpfApplication1.ServiceReference2.ToDoItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReplaceToDoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReplaceToDoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTheNumberOfToDosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTheNumberOfToDosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTheNumberOfToDosPlusXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTheNumberOfToDosPlusXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Nullable<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServerDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetServerDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiplyThreeNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MultiplyThreeNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoundTripTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RoundTripTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoundTripTest2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RoundTripTest2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveFaultExceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReceiveFaultExceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveServerInternalErrorExceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReceiveServerInternalErrorExceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference2.IService1>, WpfApplication1.ServiceReference2.IService1 {
        
        private BeginOperationDelegate onBeginGetToDosDelegate;
        
        private EndOperationDelegate onEndGetToDosDelegate;
        
        private System.Threading.SendOrPostCallback onGetToDosCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddOrUpdateToDoDelegate;
        
        private EndOperationDelegate onEndAddOrUpdateToDoDelegate;
        
        private System.Threading.SendOrPostCallback onAddOrUpdateToDoCompletedDelegate;
        
        private BeginOperationDelegate onBeginReplaceToDoDelegate;
        
        private EndOperationDelegate onEndReplaceToDoDelegate;
        
        private System.Threading.SendOrPostCallback onReplaceToDoCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteToDoDelegate;
        
        private EndOperationDelegate onEndDeleteToDoDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteToDoCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteAllToDosDelegate;
        
        private EndOperationDelegate onEndDeleteAllToDosDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteAllToDosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTheNumberOfToDosDelegate;
        
        private EndOperationDelegate onEndGetTheNumberOfToDosDelegate;
        
        private System.Threading.SendOrPostCallback onGetTheNumberOfToDosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTheNumberOfToDosPlusXDelegate;
        
        private EndOperationDelegate onEndGetTheNumberOfToDosPlusXDelegate;
        
        private System.Threading.SendOrPostCallback onGetTheNumberOfToDosPlusXCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetServerDateDelegate;
        
        private EndOperationDelegate onEndGetServerDateDelegate;
        
        private System.Threading.SendOrPostCallback onGetServerDateCompletedDelegate;
        
        private BeginOperationDelegate onBeginMultiplyThreeNumbersDelegate;
        
        private EndOperationDelegate onEndMultiplyThreeNumbersDelegate;
        
        private System.Threading.SendOrPostCallback onMultiplyThreeNumbersCompletedDelegate;
        
        private BeginOperationDelegate onBeginRoundTripTestDelegate;
        
        private EndOperationDelegate onEndRoundTripTestDelegate;
        
        private System.Threading.SendOrPostCallback onRoundTripTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginRoundTripTest2Delegate;
        
        private EndOperationDelegate onEndRoundTripTest2Delegate;
        
        private System.Threading.SendOrPostCallback onRoundTripTest2CompletedDelegate;
        
        private BeginOperationDelegate onBeginReceiveFaultExceptionDelegate;
        
        private EndOperationDelegate onEndReceiveFaultExceptionDelegate;
        
        private System.Threading.SendOrPostCallback onReceiveFaultExceptionCompletedDelegate;
        
        private BeginOperationDelegate onBeginReceiveServerInternalErrorExceptionDelegate;
        
        private EndOperationDelegate onEndReceiveServerInternalErrorExceptionDelegate;
        
        private System.Threading.SendOrPostCallback onReceiveServerInternalErrorExceptionCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetToDosCompletedEventArgs> GetToDosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddOrUpdateToDoCompleted;
        
        public event System.EventHandler<ReplaceToDoCompletedEventArgs> ReplaceToDoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteToDoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteAllToDosCompleted;
        
        public event System.EventHandler<GetTheNumberOfToDosCompletedEventArgs> GetTheNumberOfToDosCompleted;
        
        public event System.EventHandler<GetTheNumberOfToDosPlusXCompletedEventArgs> GetTheNumberOfToDosPlusXCompleted;
        
        public event System.EventHandler<GetServerDateCompletedEventArgs> GetServerDateCompleted;
        
        public event System.EventHandler<MultiplyThreeNumbersCompletedEventArgs> MultiplyThreeNumbersCompleted;
        
        public event System.EventHandler<RoundTripTestCompletedEventArgs> RoundTripTestCompleted;
        
        public event System.EventHandler<RoundTripTest2CompletedEventArgs> RoundTripTest2Completed;
        
        public event System.EventHandler<ReceiveFaultExceptionCompletedEventArgs> ReceiveFaultExceptionCompleted;
        
        public event System.EventHandler<ReceiveServerInternalErrorExceptionCompletedEventArgs> ReceiveServerInternalErrorExceptionCompleted;
        
        public WpfApplication1.ServiceReference2.ToDoItem[] GetToDos() {
            return base.Channel.GetToDos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetToDos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetToDos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WpfApplication1.ServiceReference2.ToDoItem[] EndGetToDos(System.IAsyncResult result) {
            return base.Channel.EndGetToDos(result);
        }
        
        private System.IAsyncResult OnBeginGetToDos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetToDos(callback, asyncState);
        }
        
        private object[] OnEndGetToDos(System.IAsyncResult result) {
            WpfApplication1.ServiceReference2.ToDoItem[] retVal = this.EndGetToDos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetToDosCompleted(object state) {
            if ((this.GetToDosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetToDosCompleted(this, new GetToDosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetToDosAsync() {
            this.GetToDosAsync(null);
        }
        
        public void GetToDosAsync(object userState) {
            if ((this.onBeginGetToDosDelegate == null)) {
                this.onBeginGetToDosDelegate = new BeginOperationDelegate(this.OnBeginGetToDos);
            }
            if ((this.onEndGetToDosDelegate == null)) {
                this.onEndGetToDosDelegate = new EndOperationDelegate(this.OnEndGetToDos);
            }
            if ((this.onGetToDosCompletedDelegate == null)) {
                this.onGetToDosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetToDosCompleted);
            }
            base.InvokeAsync(this.onBeginGetToDosDelegate, null, this.onEndGetToDosDelegate, this.onGetToDosCompletedDelegate, userState);
        }
        
        public void AddOrUpdateToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem) {
            base.Channel.AddOrUpdateToDo(toDoItem);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddOrUpdateToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddOrUpdateToDo(toDoItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddOrUpdateToDo(System.IAsyncResult result) {
            base.Channel.EndAddOrUpdateToDo(result);
        }
        
        private System.IAsyncResult OnBeginAddOrUpdateToDo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WpfApplication1.ServiceReference2.ToDoItem toDoItem = ((WpfApplication1.ServiceReference2.ToDoItem)(inValues[0]));
            return this.BeginAddOrUpdateToDo(toDoItem, callback, asyncState);
        }
        
        private object[] OnEndAddOrUpdateToDo(System.IAsyncResult result) {
            this.EndAddOrUpdateToDo(result);
            return null;
        }
        
        private void OnAddOrUpdateToDoCompleted(object state) {
            if ((this.AddOrUpdateToDoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddOrUpdateToDoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddOrUpdateToDoAsync(WpfApplication1.ServiceReference2.ToDoItem toDoItem) {
            this.AddOrUpdateToDoAsync(toDoItem, null);
        }
        
        public void AddOrUpdateToDoAsync(WpfApplication1.ServiceReference2.ToDoItem toDoItem, object userState) {
            if ((this.onBeginAddOrUpdateToDoDelegate == null)) {
                this.onBeginAddOrUpdateToDoDelegate = new BeginOperationDelegate(this.OnBeginAddOrUpdateToDo);
            }
            if ((this.onEndAddOrUpdateToDoDelegate == null)) {
                this.onEndAddOrUpdateToDoDelegate = new EndOperationDelegate(this.OnEndAddOrUpdateToDo);
            }
            if ((this.onAddOrUpdateToDoCompletedDelegate == null)) {
                this.onAddOrUpdateToDoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateToDoCompleted);
            }
            base.InvokeAsync(this.onBeginAddOrUpdateToDoDelegate, new object[] {
                        toDoItem}, this.onEndAddOrUpdateToDoDelegate, this.onAddOrUpdateToDoCompletedDelegate, userState);
        }
        
        public bool ReplaceToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace, WpfApplication1.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            return base.Channel.ReplaceToDo(toDoItemToReplace, newToDo, throwFaultExceptionIfNotFound);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReplaceToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace, WpfApplication1.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReplaceToDo(toDoItemToReplace, newToDo, throwFaultExceptionIfNotFound, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndReplaceToDo(System.IAsyncResult result) {
            return base.Channel.EndReplaceToDo(result);
        }
        
        private System.IAsyncResult OnBeginReplaceToDo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace = ((WpfApplication1.ServiceReference2.ToDoItem)(inValues[0]));
            WpfApplication1.ServiceReference2.ToDoItem newToDo = ((WpfApplication1.ServiceReference2.ToDoItem)(inValues[1]));
            bool throwFaultExceptionIfNotFound = ((bool)(inValues[2]));
            return this.BeginReplaceToDo(toDoItemToReplace, newToDo, throwFaultExceptionIfNotFound, callback, asyncState);
        }
        
        private object[] OnEndReplaceToDo(System.IAsyncResult result) {
            bool retVal = this.EndReplaceToDo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReplaceToDoCompleted(object state) {
            if ((this.ReplaceToDoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReplaceToDoCompleted(this, new ReplaceToDoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReplaceToDoAsync(WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace, WpfApplication1.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            this.ReplaceToDoAsync(toDoItemToReplace, newToDo, throwFaultExceptionIfNotFound, null);
        }
        
        public void ReplaceToDoAsync(WpfApplication1.ServiceReference2.ToDoItem toDoItemToReplace, WpfApplication1.ServiceReference2.ToDoItem newToDo, bool throwFaultExceptionIfNotFound, object userState) {
            if ((this.onBeginReplaceToDoDelegate == null)) {
                this.onBeginReplaceToDoDelegate = new BeginOperationDelegate(this.OnBeginReplaceToDo);
            }
            if ((this.onEndReplaceToDoDelegate == null)) {
                this.onEndReplaceToDoDelegate = new EndOperationDelegate(this.OnEndReplaceToDo);
            }
            if ((this.onReplaceToDoCompletedDelegate == null)) {
                this.onReplaceToDoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReplaceToDoCompleted);
            }
            base.InvokeAsync(this.onBeginReplaceToDoDelegate, new object[] {
                        toDoItemToReplace,
                        newToDo,
                        throwFaultExceptionIfNotFound}, this.onEndReplaceToDoDelegate, this.onReplaceToDoCompletedDelegate, userState);
        }
        
        public void DeleteToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem) {
            base.Channel.DeleteToDo(toDoItem);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteToDo(WpfApplication1.ServiceReference2.ToDoItem toDoItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteToDo(toDoItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteToDo(System.IAsyncResult result) {
            base.Channel.EndDeleteToDo(result);
        }
        
        private System.IAsyncResult OnBeginDeleteToDo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WpfApplication1.ServiceReference2.ToDoItem toDoItem = ((WpfApplication1.ServiceReference2.ToDoItem)(inValues[0]));
            return this.BeginDeleteToDo(toDoItem, callback, asyncState);
        }
        
        private object[] OnEndDeleteToDo(System.IAsyncResult result) {
            this.EndDeleteToDo(result);
            return null;
        }
        
        private void OnDeleteToDoCompleted(object state) {
            if ((this.DeleteToDoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteToDoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteToDoAsync(WpfApplication1.ServiceReference2.ToDoItem toDoItem) {
            this.DeleteToDoAsync(toDoItem, null);
        }
        
        public void DeleteToDoAsync(WpfApplication1.ServiceReference2.ToDoItem toDoItem, object userState) {
            if ((this.onBeginDeleteToDoDelegate == null)) {
                this.onBeginDeleteToDoDelegate = new BeginOperationDelegate(this.OnBeginDeleteToDo);
            }
            if ((this.onEndDeleteToDoDelegate == null)) {
                this.onEndDeleteToDoDelegate = new EndOperationDelegate(this.OnEndDeleteToDo);
            }
            if ((this.onDeleteToDoCompletedDelegate == null)) {
                this.onDeleteToDoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteToDoCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteToDoDelegate, new object[] {
                        toDoItem}, this.onEndDeleteToDoDelegate, this.onDeleteToDoCompletedDelegate, userState);
        }
        
        public void DeleteAllToDos() {
            base.Channel.DeleteAllToDos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteAllToDos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteAllToDos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteAllToDos(System.IAsyncResult result) {
            base.Channel.EndDeleteAllToDos(result);
        }
        
        private System.IAsyncResult OnBeginDeleteAllToDos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDeleteAllToDos(callback, asyncState);
        }
        
        private object[] OnEndDeleteAllToDos(System.IAsyncResult result) {
            this.EndDeleteAllToDos(result);
            return null;
        }
        
        private void OnDeleteAllToDosCompleted(object state) {
            if ((this.DeleteAllToDosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteAllToDosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAllToDosAsync() {
            this.DeleteAllToDosAsync(null);
        }
        
        public void DeleteAllToDosAsync(object userState) {
            if ((this.onBeginDeleteAllToDosDelegate == null)) {
                this.onBeginDeleteAllToDosDelegate = new BeginOperationDelegate(this.OnBeginDeleteAllToDos);
            }
            if ((this.onEndDeleteAllToDosDelegate == null)) {
                this.onEndDeleteAllToDosDelegate = new EndOperationDelegate(this.OnEndDeleteAllToDos);
            }
            if ((this.onDeleteAllToDosCompletedDelegate == null)) {
                this.onDeleteAllToDosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteAllToDosCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteAllToDosDelegate, null, this.onEndDeleteAllToDosDelegate, this.onDeleteAllToDosCompletedDelegate, userState);
        }
        
        public int GetTheNumberOfToDos() {
            return base.Channel.GetTheNumberOfToDos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTheNumberOfToDos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTheNumberOfToDos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetTheNumberOfToDos(System.IAsyncResult result) {
            return base.Channel.EndGetTheNumberOfToDos(result);
        }
        
        private System.IAsyncResult OnBeginGetTheNumberOfToDos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetTheNumberOfToDos(callback, asyncState);
        }
        
        private object[] OnEndGetTheNumberOfToDos(System.IAsyncResult result) {
            int retVal = this.EndGetTheNumberOfToDos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTheNumberOfToDosCompleted(object state) {
            if ((this.GetTheNumberOfToDosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTheNumberOfToDosCompleted(this, new GetTheNumberOfToDosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTheNumberOfToDosAsync() {
            this.GetTheNumberOfToDosAsync(null);
        }
        
        public void GetTheNumberOfToDosAsync(object userState) {
            if ((this.onBeginGetTheNumberOfToDosDelegate == null)) {
                this.onBeginGetTheNumberOfToDosDelegate = new BeginOperationDelegate(this.OnBeginGetTheNumberOfToDos);
            }
            if ((this.onEndGetTheNumberOfToDosDelegate == null)) {
                this.onEndGetTheNumberOfToDosDelegate = new EndOperationDelegate(this.OnEndGetTheNumberOfToDos);
            }
            if ((this.onGetTheNumberOfToDosCompletedDelegate == null)) {
                this.onGetTheNumberOfToDosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTheNumberOfToDosCompleted);
            }
            base.InvokeAsync(this.onBeginGetTheNumberOfToDosDelegate, null, this.onEndGetTheNumberOfToDosDelegate, this.onGetTheNumberOfToDosCompletedDelegate, userState);
        }
        
        public System.Nullable<int> GetTheNumberOfToDosPlusX(int x) {
            return base.Channel.GetTheNumberOfToDosPlusX(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTheNumberOfToDosPlusX(int x, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTheNumberOfToDosPlusX(x, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Nullable<int> EndGetTheNumberOfToDosPlusX(System.IAsyncResult result) {
            return base.Channel.EndGetTheNumberOfToDosPlusX(result);
        }
        
        private System.IAsyncResult OnBeginGetTheNumberOfToDosPlusX(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            return this.BeginGetTheNumberOfToDosPlusX(x, callback, asyncState);
        }
        
        private object[] OnEndGetTheNumberOfToDosPlusX(System.IAsyncResult result) {
            System.Nullable<int> retVal = this.EndGetTheNumberOfToDosPlusX(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTheNumberOfToDosPlusXCompleted(object state) {
            if ((this.GetTheNumberOfToDosPlusXCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTheNumberOfToDosPlusXCompleted(this, new GetTheNumberOfToDosPlusXCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTheNumberOfToDosPlusXAsync(int x) {
            this.GetTheNumberOfToDosPlusXAsync(x, null);
        }
        
        public void GetTheNumberOfToDosPlusXAsync(int x, object userState) {
            if ((this.onBeginGetTheNumberOfToDosPlusXDelegate == null)) {
                this.onBeginGetTheNumberOfToDosPlusXDelegate = new BeginOperationDelegate(this.OnBeginGetTheNumberOfToDosPlusX);
            }
            if ((this.onEndGetTheNumberOfToDosPlusXDelegate == null)) {
                this.onEndGetTheNumberOfToDosPlusXDelegate = new EndOperationDelegate(this.OnEndGetTheNumberOfToDosPlusX);
            }
            if ((this.onGetTheNumberOfToDosPlusXCompletedDelegate == null)) {
                this.onGetTheNumberOfToDosPlusXCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTheNumberOfToDosPlusXCompleted);
            }
            base.InvokeAsync(this.onBeginGetTheNumberOfToDosPlusXDelegate, new object[] {
                        x}, this.onEndGetTheNumberOfToDosPlusXDelegate, this.onGetTheNumberOfToDosPlusXCompletedDelegate, userState);
        }
        
        public System.DateTime GetServerDate() {
            return base.Channel.GetServerDate();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetServerDate(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetServerDate(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.DateTime EndGetServerDate(System.IAsyncResult result) {
            return base.Channel.EndGetServerDate(result);
        }
        
        private System.IAsyncResult OnBeginGetServerDate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetServerDate(callback, asyncState);
        }
        
        private object[] OnEndGetServerDate(System.IAsyncResult result) {
            System.DateTime retVal = this.EndGetServerDate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetServerDateCompleted(object state) {
            if ((this.GetServerDateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetServerDateCompleted(this, new GetServerDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetServerDateAsync() {
            this.GetServerDateAsync(null);
        }
        
        public void GetServerDateAsync(object userState) {
            if ((this.onBeginGetServerDateDelegate == null)) {
                this.onBeginGetServerDateDelegate = new BeginOperationDelegate(this.OnBeginGetServerDate);
            }
            if ((this.onEndGetServerDateDelegate == null)) {
                this.onEndGetServerDateDelegate = new EndOperationDelegate(this.OnEndGetServerDate);
            }
            if ((this.onGetServerDateCompletedDelegate == null)) {
                this.onGetServerDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetServerDateCompleted);
            }
            base.InvokeAsync(this.onBeginGetServerDateDelegate, null, this.onEndGetServerDateDelegate, this.onGetServerDateCompletedDelegate, userState);
        }
        
        public double MultiplyThreeNumbers(double x1, double x2, double x3) {
            return base.Channel.MultiplyThreeNumbers(x1, x2, x3);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMultiplyThreeNumbers(double x1, double x2, double x3, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMultiplyThreeNumbers(x1, x2, x3, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndMultiplyThreeNumbers(System.IAsyncResult result) {
            return base.Channel.EndMultiplyThreeNumbers(result);
        }
        
        private System.IAsyncResult OnBeginMultiplyThreeNumbers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double x1 = ((double)(inValues[0]));
            double x2 = ((double)(inValues[1]));
            double x3 = ((double)(inValues[2]));
            return this.BeginMultiplyThreeNumbers(x1, x2, x3, callback, asyncState);
        }
        
        private object[] OnEndMultiplyThreeNumbers(System.IAsyncResult result) {
            double retVal = this.EndMultiplyThreeNumbers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMultiplyThreeNumbersCompleted(object state) {
            if ((this.MultiplyThreeNumbersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MultiplyThreeNumbersCompleted(this, new MultiplyThreeNumbersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MultiplyThreeNumbersAsync(double x1, double x2, double x3) {
            this.MultiplyThreeNumbersAsync(x1, x2, x3, null);
        }
        
        public void MultiplyThreeNumbersAsync(double x1, double x2, double x3, object userState) {
            if ((this.onBeginMultiplyThreeNumbersDelegate == null)) {
                this.onBeginMultiplyThreeNumbersDelegate = new BeginOperationDelegate(this.OnBeginMultiplyThreeNumbers);
            }
            if ((this.onEndMultiplyThreeNumbersDelegate == null)) {
                this.onEndMultiplyThreeNumbersDelegate = new EndOperationDelegate(this.OnEndMultiplyThreeNumbers);
            }
            if ((this.onMultiplyThreeNumbersCompletedDelegate == null)) {
                this.onMultiplyThreeNumbersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMultiplyThreeNumbersCompleted);
            }
            base.InvokeAsync(this.onBeginMultiplyThreeNumbersDelegate, new object[] {
                        x1,
                        x2,
                        x3}, this.onEndMultiplyThreeNumbersDelegate, this.onMultiplyThreeNumbersCompletedDelegate, userState);
        }
        
        public object RoundTripTest(object obj) {
            return base.Channel.RoundTripTest(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRoundTripTest(object obj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRoundTripTest(obj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public object EndRoundTripTest(System.IAsyncResult result) {
            return base.Channel.EndRoundTripTest(result);
        }
        
        private System.IAsyncResult OnBeginRoundTripTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            object obj = ((object)(inValues[0]));
            return this.BeginRoundTripTest(obj, callback, asyncState);
        }
        
        private object[] OnEndRoundTripTest(System.IAsyncResult result) {
            object retVal = this.EndRoundTripTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRoundTripTestCompleted(object state) {
            if ((this.RoundTripTestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RoundTripTestCompleted(this, new RoundTripTestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RoundTripTestAsync(object obj) {
            this.RoundTripTestAsync(obj, null);
        }
        
        public void RoundTripTestAsync(object obj, object userState) {
            if ((this.onBeginRoundTripTestDelegate == null)) {
                this.onBeginRoundTripTestDelegate = new BeginOperationDelegate(this.OnBeginRoundTripTest);
            }
            if ((this.onEndRoundTripTestDelegate == null)) {
                this.onEndRoundTripTestDelegate = new EndOperationDelegate(this.OnEndRoundTripTest);
            }
            if ((this.onRoundTripTestCompletedDelegate == null)) {
                this.onRoundTripTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRoundTripTestCompleted);
            }
            base.InvokeAsync(this.onBeginRoundTripTestDelegate, new object[] {
                        obj}, this.onEndRoundTripTestDelegate, this.onRoundTripTestCompletedDelegate, userState);
        }
        
        public object RoundTripTest2(object obj) {
            return base.Channel.RoundTripTest2(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRoundTripTest2(object obj, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRoundTripTest2(obj, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public object EndRoundTripTest2(System.IAsyncResult result) {
            return base.Channel.EndRoundTripTest2(result);
        }
        
        private System.IAsyncResult OnBeginRoundTripTest2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            object obj = ((object)(inValues[0]));
            return this.BeginRoundTripTest2(obj, callback, asyncState);
        }
        
        private object[] OnEndRoundTripTest2(System.IAsyncResult result) {
            object retVal = this.EndRoundTripTest2(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRoundTripTest2Completed(object state) {
            if ((this.RoundTripTest2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RoundTripTest2Completed(this, new RoundTripTest2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RoundTripTest2Async(object obj) {
            this.RoundTripTest2Async(obj, null);
        }
        
        public void RoundTripTest2Async(object obj, object userState) {
            if ((this.onBeginRoundTripTest2Delegate == null)) {
                this.onBeginRoundTripTest2Delegate = new BeginOperationDelegate(this.OnBeginRoundTripTest2);
            }
            if ((this.onEndRoundTripTest2Delegate == null)) {
                this.onEndRoundTripTest2Delegate = new EndOperationDelegate(this.OnEndRoundTripTest2);
            }
            if ((this.onRoundTripTest2CompletedDelegate == null)) {
                this.onRoundTripTest2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRoundTripTest2Completed);
            }
            base.InvokeAsync(this.onBeginRoundTripTest2Delegate, new object[] {
                        obj}, this.onEndRoundTripTest2Delegate, this.onRoundTripTest2CompletedDelegate, userState);
        }
        
        public bool ReceiveFaultException() {
            return base.Channel.ReceiveFaultException();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReceiveFaultException(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReceiveFaultException(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndReceiveFaultException(System.IAsyncResult result) {
            return base.Channel.EndReceiveFaultException(result);
        }
        
        private System.IAsyncResult OnBeginReceiveFaultException(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginReceiveFaultException(callback, asyncState);
        }
        
        private object[] OnEndReceiveFaultException(System.IAsyncResult result) {
            bool retVal = this.EndReceiveFaultException(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReceiveFaultExceptionCompleted(object state) {
            if ((this.ReceiveFaultExceptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReceiveFaultExceptionCompleted(this, new ReceiveFaultExceptionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReceiveFaultExceptionAsync() {
            this.ReceiveFaultExceptionAsync(null);
        }
        
        public void ReceiveFaultExceptionAsync(object userState) {
            if ((this.onBeginReceiveFaultExceptionDelegate == null)) {
                this.onBeginReceiveFaultExceptionDelegate = new BeginOperationDelegate(this.OnBeginReceiveFaultException);
            }
            if ((this.onEndReceiveFaultExceptionDelegate == null)) {
                this.onEndReceiveFaultExceptionDelegate = new EndOperationDelegate(this.OnEndReceiveFaultException);
            }
            if ((this.onReceiveFaultExceptionCompletedDelegate == null)) {
                this.onReceiveFaultExceptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceiveFaultExceptionCompleted);
            }
            base.InvokeAsync(this.onBeginReceiveFaultExceptionDelegate, null, this.onEndReceiveFaultExceptionDelegate, this.onReceiveFaultExceptionCompletedDelegate, userState);
        }
        
        public bool ReceiveServerInternalErrorException() {
            return base.Channel.ReceiveServerInternalErrorException();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReceiveServerInternalErrorException(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReceiveServerInternalErrorException(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndReceiveServerInternalErrorException(System.IAsyncResult result) {
            return base.Channel.EndReceiveServerInternalErrorException(result);
        }
        
        private System.IAsyncResult OnBeginReceiveServerInternalErrorException(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginReceiveServerInternalErrorException(callback, asyncState);
        }
        
        private object[] OnEndReceiveServerInternalErrorException(System.IAsyncResult result) {
            bool retVal = this.EndReceiveServerInternalErrorException(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReceiveServerInternalErrorExceptionCompleted(object state) {
            if ((this.ReceiveServerInternalErrorExceptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReceiveServerInternalErrorExceptionCompleted(this, new ReceiveServerInternalErrorExceptionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReceiveServerInternalErrorExceptionAsync() {
            this.ReceiveServerInternalErrorExceptionAsync(null);
        }
        
        public void ReceiveServerInternalErrorExceptionAsync(object userState) {
            if ((this.onBeginReceiveServerInternalErrorExceptionDelegate == null)) {
                this.onBeginReceiveServerInternalErrorExceptionDelegate = new BeginOperationDelegate(this.OnBeginReceiveServerInternalErrorException);
            }
            if ((this.onEndReceiveServerInternalErrorExceptionDelegate == null)) {
                this.onEndReceiveServerInternalErrorExceptionDelegate = new EndOperationDelegate(this.OnEndReceiveServerInternalErrorException);
            }
            if ((this.onReceiveServerInternalErrorExceptionCompletedDelegate == null)) {
                this.onReceiveServerInternalErrorExceptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReceiveServerInternalErrorExceptionCompleted);
            }
            base.InvokeAsync(this.onBeginReceiveServerInternalErrorExceptionDelegate, null, this.onEndReceiveServerInternalErrorExceptionDelegate, this.onReceiveServerInternalErrorExceptionCompletedDelegate, userState);
        }
    }
}
