//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        private System.Nullable<int> NullableTest1Field;
        
        private System.Nullable<int> NullableTest2Field;
        
        private System.Nullable<System.DateTime> NullableTest3Field;
        
        private System.Nullable<System.DateTime> NullableTest4Field;
        
        private char CharValueField;
        
        private TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoImportance ImportanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ArrayOfString TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> NullableTest1 {
            get {
                return this.NullableTest1Field;
            }
            set {
                if ((this.NullableTest1Field.Equals(value) != true)) {
                    this.NullableTest1Field = value;
                    this.RaisePropertyChanged("NullableTest1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> NullableTest2 {
            get {
                return this.NullableTest2Field;
            }
            set {
                if ((this.NullableTest2Field.Equals(value) != true)) {
                    this.NullableTest2Field = value;
                    this.RaisePropertyChanged("NullableTest2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> NullableTest3 {
            get {
                return this.NullableTest3Field;
            }
            set {
                if ((this.NullableTest3Field.Equals(value) != true)) {
                    this.NullableTest3Field = value;
                    this.RaisePropertyChanged("NullableTest3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> NullableTest4 {
            get {
                return this.NullableTest4Field;
            }
            set {
                if ((this.NullableTest4Field.Equals(value) != true)) {
                    this.NullableTest4Field = value;
                    this.RaisePropertyChanged("NullableTest4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public char CharValue {
            get {
                return this.CharValueField;
            }
            set {
                if ((this.CharValueField.Equals(value) != true)) {
                    this.CharValueField = value;
                    this.RaisePropertyChanged("CharValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoImportance Importance {
            get {
                return this.ImportanceField;
            }
            set {
                if ((this.ImportanceField.Equals(value) != true)) {
                    this.ImportanceField = value;
                    this.RaisePropertyChanged("Importance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ArrayOfString Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoImportance", Namespace="http://tempuri.org/")]
    public enum ToDoImportance : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4_EventBasedAsync_XmlSerializer.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since element name GetToDosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponse GetToDos(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetToDos", ReplyAction="http://tempuri.org/IService1/GetToDosResponse")]
        System.IAsyncResult BeginGetToDos(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest request, System.AsyncCallback callback, object asyncState);
        
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponse EndGetToDos(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name toDoItem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponse AddOrUpdateToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddOrUpdateToDo", ReplyAction="http://tempuri.org/IService1/AddOrUpdateToDoResponse")]
        System.IAsyncResult BeginAddOrUpdateToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest request, System.AsyncCallback callback, object asyncState);
        
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponse EndAddOrUpdateToDo(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name toDoItemToReplace from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReplaceToDo", ReplyAction="http://tempuri.org/IService1/ReplaceToDoResponse")]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponse ReplaceToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ReplaceToDo", ReplyAction="http://tempuri.org/IService1/ReplaceToDoResponse")]
        System.IAsyncResult BeginReplaceToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest request, System.AsyncCallback callback, object asyncState);
        
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponse EndReplaceToDo(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name toDoItem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponse DeleteToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteToDo", ReplyAction="http://tempuri.org/IService1/DeleteToDoResponse")]
        System.IAsyncResult BeginDeleteToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest request, System.AsyncCallback callback, object asyncState);
        
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponse EndDeleteToDo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllToDos", ReplyAction="http://tempuri.org/IService1/DeleteAllToDosResponse")]
        void DeleteAllToDos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteAllToDos", ReplyAction="http://tempuri.org/IService1/DeleteAllToDosResponse")]
        System.IAsyncResult BeginDeleteAllToDos(System.AsyncCallback callback, object asyncState);
        
        void EndDeleteAllToDos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDos", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosResponse")]
        int GetTheNumberOfToDos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTheNumberOfToDos", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosResponse")]
        System.IAsyncResult BeginGetTheNumberOfToDos(System.AsyncCallback callback, object asyncState);
        
        int EndGetTheNumberOfToDos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheNumberOfToDosPlusX", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosPlusXResponse")]
        System.Nullable<int> GetTheNumberOfToDosPlusX(int x);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTheNumberOfToDosPlusX", ReplyAction="http://tempuri.org/IService1/GetTheNumberOfToDosPlusXResponse")]
        System.IAsyncResult BeginGetTheNumberOfToDosPlusX(int x, System.AsyncCallback callback, object asyncState);
        
        System.Nullable<int> EndGetTheNumberOfToDosPlusX(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServerDate", ReplyAction="http://tempuri.org/IService1/GetServerDateResponse")]
        System.DateTime GetServerDate();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetServerDate", ReplyAction="http://tempuri.org/IService1/GetServerDateResponse")]
        System.IAsyncResult BeginGetServerDate(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndGetServerDate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplyThreeNumbers", ReplyAction="http://tempuri.org/IService1/MultiplyThreeNumbersResponse")]
        double MultiplyThreeNumbers(double x1, double x2, double x3);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/MultiplyThreeNumbers", ReplyAction="http://tempuri.org/IService1/MultiplyThreeNumbersResponse")]
        System.IAsyncResult BeginMultiplyThreeNumbers(double x1, double x2, double x3, System.AsyncCallback callback, object asyncState);
        
        double EndMultiplyThreeNumbers(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDos", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequestBody Body;
        
        public GetToDosRequest() {
        }
        
        public GetToDosRequest(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetToDosRequestBody {
        
        public GetToDosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToDosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToDosResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponseBody Body;
        
        public GetToDosResponse() {
        }
        
        public GetToDosResponse(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToDosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[] GetToDosResult;
        
        public GetToDosResponseBody() {
        }
        
        public GetToDosResponseBody(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[] GetToDosResult) {
            this.GetToDosResult = GetToDosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDo", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequestBody Body;
        
        public AddOrUpdateToDoRequest() {
        }
        
        public AddOrUpdateToDoRequest(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrUpdateToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem;
        
        public AddOrUpdateToDoRequestBody() {
        }
        
        public AddOrUpdateToDoRequestBody(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem) {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrUpdateToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrUpdateToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponseBody Body;
        
        public AddOrUpdateToDoResponse() {
        }
        
        public AddOrUpdateToDoResponse(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddOrUpdateToDoResponseBody {
        
        public AddOrUpdateToDoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplaceToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReplaceToDo", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequestBody Body;
        
        public ReplaceToDoRequest() {
        }
        
        public ReplaceToDoRequest(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplaceToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool throwFaultExceptionIfNotFound;
        
        public ReplaceToDoRequestBody() {
        }
        
        public ReplaceToDoRequestBody(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            this.toDoItemToReplace = toDoItemToReplace;
            this.newToDo = newToDo;
            this.throwFaultExceptionIfNotFound = throwFaultExceptionIfNotFound;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplaceToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReplaceToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponseBody Body;
        
        public ReplaceToDoResponse() {
        }
        
        public ReplaceToDoResponse(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplaceToDoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReplaceToDoResult;
        
        public ReplaceToDoResponseBody() {
        }
        
        public ReplaceToDoResponseBody(bool ReplaceToDoResult) {
            this.ReplaceToDoResult = ReplaceToDoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDo", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequestBody Body;
        
        public DeleteToDoRequest() {
        }
        
        public DeleteToDoRequest(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem;
        
        public DeleteToDoRequestBody() {
        }
        
        public DeleteToDoRequestBody(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem) {
            this.toDoItem = toDoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponseBody Body;
        
        public DeleteToDoResponse() {
        }
        
        public DeleteToDoResponse(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteToDoResponseBody {
        
        public DeleteToDoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetToDosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetToDosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReplaceToDoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReplaceToDoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTheNumberOfToDosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTheNumberOfToDosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTheNumberOfToDosPlusXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTheNumberOfToDosPlusXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Nullable<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServerDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetServerDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiplyThreeNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MultiplyThreeNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1>, TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1 {
        
        private BeginOperationDelegate onBeginGetToDosDelegate;
        
        private EndOperationDelegate onEndGetToDosDelegate;
        
        private System.Threading.SendOrPostCallback onGetToDosCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddOrUpdateToDoDelegate;
        
        private EndOperationDelegate onEndAddOrUpdateToDoDelegate;
        
        private System.Threading.SendOrPostCallback onAddOrUpdateToDoCompletedDelegate;
        
        private BeginOperationDelegate onBeginReplaceToDoDelegate;
        
        private EndOperationDelegate onEndReplaceToDoDelegate;
        
        private System.Threading.SendOrPostCallback onReplaceToDoCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteToDoDelegate;
        
        private EndOperationDelegate onEndDeleteToDoDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteToDoCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteAllToDosDelegate;
        
        private EndOperationDelegate onEndDeleteAllToDosDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteAllToDosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTheNumberOfToDosDelegate;
        
        private EndOperationDelegate onEndGetTheNumberOfToDosDelegate;
        
        private System.Threading.SendOrPostCallback onGetTheNumberOfToDosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTheNumberOfToDosPlusXDelegate;
        
        private EndOperationDelegate onEndGetTheNumberOfToDosPlusXDelegate;
        
        private System.Threading.SendOrPostCallback onGetTheNumberOfToDosPlusXCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetServerDateDelegate;
        
        private EndOperationDelegate onEndGetServerDateDelegate;
        
        private System.Threading.SendOrPostCallback onGetServerDateCompletedDelegate;
        
        private BeginOperationDelegate onBeginMultiplyThreeNumbersDelegate;
        
        private EndOperationDelegate onEndMultiplyThreeNumbersDelegate;
        
        private System.Threading.SendOrPostCallback onMultiplyThreeNumbersCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetToDosCompletedEventArgs> GetToDosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddOrUpdateToDoCompleted;
        
        public event System.EventHandler<ReplaceToDoCompletedEventArgs> ReplaceToDoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteToDoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteAllToDosCompleted;
        
        public event System.EventHandler<GetTheNumberOfToDosCompletedEventArgs> GetTheNumberOfToDosCompleted;
        
        public event System.EventHandler<GetTheNumberOfToDosPlusXCompletedEventArgs> GetTheNumberOfToDosPlusXCompleted;
        
        public event System.EventHandler<GetServerDateCompletedEventArgs> GetServerDateCompleted;
        
        public event System.EventHandler<MultiplyThreeNumbersCompletedEventArgs> MultiplyThreeNumbersCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.GetToDos(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest request) {
            return base.Channel.GetToDos(request);
        }
        
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[] GetToDos() {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequestBody();
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).GetToDos(inValue);
            return retVal.Body.GetToDosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.BeginGetToDos(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetToDos(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetToDos(System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosRequestBody();
            return ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).BeginGetToDos(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.EndGetToDos(System.IAsyncResult result) {
            return base.Channel.EndGetToDos(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[] EndGetToDos(System.IAsyncResult result) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.GetToDosResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).EndGetToDos(result);
            return retVal.Body.GetToDosResult;
        }
        
        private System.IAsyncResult OnBeginGetToDos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetToDos(callback, asyncState);
        }
        
        private object[] OnEndGetToDos(System.IAsyncResult result) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem[] retVal = this.EndGetToDos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetToDosCompleted(object state) {
            if ((this.GetToDosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetToDosCompleted(this, new GetToDosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetToDosAsync() {
            this.GetToDosAsync(null);
        }
        
        public void GetToDosAsync(object userState) {
            if ((this.onBeginGetToDosDelegate == null)) {
                this.onBeginGetToDosDelegate = new BeginOperationDelegate(this.OnBeginGetToDos);
            }
            if ((this.onEndGetToDosDelegate == null)) {
                this.onEndGetToDosDelegate = new EndOperationDelegate(this.OnEndGetToDos);
            }
            if ((this.onGetToDosCompletedDelegate == null)) {
                this.onGetToDosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetToDosCompleted);
            }
            base.InvokeAsync(this.onBeginGetToDosDelegate, null, this.onEndGetToDosDelegate, this.onGetToDosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.AddOrUpdateToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest request) {
            return base.Channel.AddOrUpdateToDo(request);
        }
        
        public void AddOrUpdateToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).AddOrUpdateToDo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.BeginAddOrUpdateToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddOrUpdateToDo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddOrUpdateToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem, System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).BeginAddOrUpdateToDo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.EndAddOrUpdateToDo(System.IAsyncResult result) {
            return base.Channel.EndAddOrUpdateToDo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddOrUpdateToDo(System.IAsyncResult result) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.AddOrUpdateToDoResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).EndAddOrUpdateToDo(result);
        }
        
        private System.IAsyncResult OnBeginAddOrUpdateToDo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem)(inValues[0]));
            return this.BeginAddOrUpdateToDo(toDoItem, callback, asyncState);
        }
        
        private object[] OnEndAddOrUpdateToDo(System.IAsyncResult result) {
            this.EndAddOrUpdateToDo(result);
            return null;
        }
        
        private void OnAddOrUpdateToDoCompleted(object state) {
            if ((this.AddOrUpdateToDoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddOrUpdateToDoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddOrUpdateToDoAsync(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem) {
            this.AddOrUpdateToDoAsync(toDoItem, null);
        }
        
        public void AddOrUpdateToDoAsync(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem, object userState) {
            if ((this.onBeginAddOrUpdateToDoDelegate == null)) {
                this.onBeginAddOrUpdateToDoDelegate = new BeginOperationDelegate(this.OnBeginAddOrUpdateToDo);
            }
            if ((this.onEndAddOrUpdateToDoDelegate == null)) {
                this.onEndAddOrUpdateToDoDelegate = new EndOperationDelegate(this.OnEndAddOrUpdateToDo);
            }
            if ((this.onAddOrUpdateToDoCompletedDelegate == null)) {
                this.onAddOrUpdateToDoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateToDoCompleted);
            }
            base.InvokeAsync(this.onBeginAddOrUpdateToDoDelegate, new object[] {
                        toDoItem}, this.onEndAddOrUpdateToDoDelegate, this.onAddOrUpdateToDoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.ReplaceToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest request) {
            return base.Channel.ReplaceToDo(request);
        }
        
        public bool ReplaceToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequestBody();
            inValue.Body.toDoItemToReplace = toDoItemToReplace;
            inValue.Body.newToDo = newToDo;
            inValue.Body.throwFaultExceptionIfNotFound = throwFaultExceptionIfNotFound;
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).ReplaceToDo(inValue);
            return retVal.Body.ReplaceToDoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.BeginReplaceToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReplaceToDo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReplaceToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo, bool throwFaultExceptionIfNotFound, System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoRequestBody();
            inValue.Body.toDoItemToReplace = toDoItemToReplace;
            inValue.Body.newToDo = newToDo;
            inValue.Body.throwFaultExceptionIfNotFound = throwFaultExceptionIfNotFound;
            return ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).BeginReplaceToDo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.EndReplaceToDo(System.IAsyncResult result) {
            return base.Channel.EndReplaceToDo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndReplaceToDo(System.IAsyncResult result) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ReplaceToDoResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).EndReplaceToDo(result);
            return retVal.Body.ReplaceToDoResult;
        }
        
        private System.IAsyncResult OnBeginReplaceToDo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem)(inValues[0]));
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem)(inValues[1]));
            bool throwFaultExceptionIfNotFound = ((bool)(inValues[2]));
            return this.BeginReplaceToDo(toDoItemToReplace, newToDo, throwFaultExceptionIfNotFound, callback, asyncState);
        }
        
        private object[] OnEndReplaceToDo(System.IAsyncResult result) {
            bool retVal = this.EndReplaceToDo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReplaceToDoCompleted(object state) {
            if ((this.ReplaceToDoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReplaceToDoCompleted(this, new ReplaceToDoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReplaceToDoAsync(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo, bool throwFaultExceptionIfNotFound) {
            this.ReplaceToDoAsync(toDoItemToReplace, newToDo, throwFaultExceptionIfNotFound, null);
        }
        
        public void ReplaceToDoAsync(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItemToReplace, TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem newToDo, bool throwFaultExceptionIfNotFound, object userState) {
            if ((this.onBeginReplaceToDoDelegate == null)) {
                this.onBeginReplaceToDoDelegate = new BeginOperationDelegate(this.OnBeginReplaceToDo);
            }
            if ((this.onEndReplaceToDoDelegate == null)) {
                this.onEndReplaceToDoDelegate = new EndOperationDelegate(this.OnEndReplaceToDo);
            }
            if ((this.onReplaceToDoCompletedDelegate == null)) {
                this.onReplaceToDoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReplaceToDoCompleted);
            }
            base.InvokeAsync(this.onBeginReplaceToDoDelegate, new object[] {
                        toDoItemToReplace,
                        newToDo,
                        throwFaultExceptionIfNotFound}, this.onEndReplaceToDoDelegate, this.onReplaceToDoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.DeleteToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest request) {
            return base.Channel.DeleteToDo(request);
        }
        
        public void DeleteToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).DeleteToDo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.BeginDeleteToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteToDo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteToDo(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem, System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest inValue = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequest();
            inValue.Body = new TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoRequestBody();
            inValue.Body.toDoItem = toDoItem;
            return ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).BeginDeleteToDo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponse TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1.EndDeleteToDo(System.IAsyncResult result) {
            return base.Channel.EndDeleteToDo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteToDo(System.IAsyncResult result) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.DeleteToDoResponse retVal = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.IService1)(this)).EndDeleteToDo(result);
        }
        
        private System.IAsyncResult OnBeginDeleteToDo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem = ((TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem)(inValues[0]));
            return this.BeginDeleteToDo(toDoItem, callback, asyncState);
        }
        
        private object[] OnEndDeleteToDo(System.IAsyncResult result) {
            this.EndDeleteToDo(result);
            return null;
        }
        
        private void OnDeleteToDoCompleted(object state) {
            if ((this.DeleteToDoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteToDoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteToDoAsync(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem) {
            this.DeleteToDoAsync(toDoItem, null);
        }
        
        public void DeleteToDoAsync(TestCshtml5WCF.ServiceReference4_EventBasedAsync_XmlSerializer.ToDoItem toDoItem, object userState) {
            if ((this.onBeginDeleteToDoDelegate == null)) {
                this.onBeginDeleteToDoDelegate = new BeginOperationDelegate(this.OnBeginDeleteToDo);
            }
            if ((this.onEndDeleteToDoDelegate == null)) {
                this.onEndDeleteToDoDelegate = new EndOperationDelegate(this.OnEndDeleteToDo);
            }
            if ((this.onDeleteToDoCompletedDelegate == null)) {
                this.onDeleteToDoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteToDoCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteToDoDelegate, new object[] {
                        toDoItem}, this.onEndDeleteToDoDelegate, this.onDeleteToDoCompletedDelegate, userState);
        }
        
        public void DeleteAllToDos() {
            base.Channel.DeleteAllToDos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteAllToDos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteAllToDos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDeleteAllToDos(System.IAsyncResult result) {
            base.Channel.EndDeleteAllToDos(result);
        }
        
        private System.IAsyncResult OnBeginDeleteAllToDos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDeleteAllToDos(callback, asyncState);
        }
        
        private object[] OnEndDeleteAllToDos(System.IAsyncResult result) {
            this.EndDeleteAllToDos(result);
            return null;
        }
        
        private void OnDeleteAllToDosCompleted(object state) {
            if ((this.DeleteAllToDosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteAllToDosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAllToDosAsync() {
            this.DeleteAllToDosAsync(null);
        }
        
        public void DeleteAllToDosAsync(object userState) {
            if ((this.onBeginDeleteAllToDosDelegate == null)) {
                this.onBeginDeleteAllToDosDelegate = new BeginOperationDelegate(this.OnBeginDeleteAllToDos);
            }
            if ((this.onEndDeleteAllToDosDelegate == null)) {
                this.onEndDeleteAllToDosDelegate = new EndOperationDelegate(this.OnEndDeleteAllToDos);
            }
            if ((this.onDeleteAllToDosCompletedDelegate == null)) {
                this.onDeleteAllToDosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteAllToDosCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteAllToDosDelegate, null, this.onEndDeleteAllToDosDelegate, this.onDeleteAllToDosCompletedDelegate, userState);
        }
        
        public int GetTheNumberOfToDos() {
            return base.Channel.GetTheNumberOfToDos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTheNumberOfToDos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTheNumberOfToDos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetTheNumberOfToDos(System.IAsyncResult result) {
            return base.Channel.EndGetTheNumberOfToDos(result);
        }
        
        private System.IAsyncResult OnBeginGetTheNumberOfToDos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetTheNumberOfToDos(callback, asyncState);
        }
        
        private object[] OnEndGetTheNumberOfToDos(System.IAsyncResult result) {
            int retVal = this.EndGetTheNumberOfToDos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTheNumberOfToDosCompleted(object state) {
            if ((this.GetTheNumberOfToDosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTheNumberOfToDosCompleted(this, new GetTheNumberOfToDosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTheNumberOfToDosAsync() {
            this.GetTheNumberOfToDosAsync(null);
        }
        
        public void GetTheNumberOfToDosAsync(object userState) {
            if ((this.onBeginGetTheNumberOfToDosDelegate == null)) {
                this.onBeginGetTheNumberOfToDosDelegate = new BeginOperationDelegate(this.OnBeginGetTheNumberOfToDos);
            }
            if ((this.onEndGetTheNumberOfToDosDelegate == null)) {
                this.onEndGetTheNumberOfToDosDelegate = new EndOperationDelegate(this.OnEndGetTheNumberOfToDos);
            }
            if ((this.onGetTheNumberOfToDosCompletedDelegate == null)) {
                this.onGetTheNumberOfToDosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTheNumberOfToDosCompleted);
            }
            base.InvokeAsync(this.onBeginGetTheNumberOfToDosDelegate, null, this.onEndGetTheNumberOfToDosDelegate, this.onGetTheNumberOfToDosCompletedDelegate, userState);
        }
        
        public System.Nullable<int> GetTheNumberOfToDosPlusX(int x) {
            return base.Channel.GetTheNumberOfToDosPlusX(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTheNumberOfToDosPlusX(int x, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTheNumberOfToDosPlusX(x, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Nullable<int> EndGetTheNumberOfToDosPlusX(System.IAsyncResult result) {
            return base.Channel.EndGetTheNumberOfToDosPlusX(result);
        }
        
        private System.IAsyncResult OnBeginGetTheNumberOfToDosPlusX(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            return this.BeginGetTheNumberOfToDosPlusX(x, callback, asyncState);
        }
        
        private object[] OnEndGetTheNumberOfToDosPlusX(System.IAsyncResult result) {
            System.Nullable<int> retVal = this.EndGetTheNumberOfToDosPlusX(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTheNumberOfToDosPlusXCompleted(object state) {
            if ((this.GetTheNumberOfToDosPlusXCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTheNumberOfToDosPlusXCompleted(this, new GetTheNumberOfToDosPlusXCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTheNumberOfToDosPlusXAsync(int x) {
            this.GetTheNumberOfToDosPlusXAsync(x, null);
        }
        
        public void GetTheNumberOfToDosPlusXAsync(int x, object userState) {
            if ((this.onBeginGetTheNumberOfToDosPlusXDelegate == null)) {
                this.onBeginGetTheNumberOfToDosPlusXDelegate = new BeginOperationDelegate(this.OnBeginGetTheNumberOfToDosPlusX);
            }
            if ((this.onEndGetTheNumberOfToDosPlusXDelegate == null)) {
                this.onEndGetTheNumberOfToDosPlusXDelegate = new EndOperationDelegate(this.OnEndGetTheNumberOfToDosPlusX);
            }
            if ((this.onGetTheNumberOfToDosPlusXCompletedDelegate == null)) {
                this.onGetTheNumberOfToDosPlusXCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTheNumberOfToDosPlusXCompleted);
            }
            base.InvokeAsync(this.onBeginGetTheNumberOfToDosPlusXDelegate, new object[] {
                        x}, this.onEndGetTheNumberOfToDosPlusXDelegate, this.onGetTheNumberOfToDosPlusXCompletedDelegate, userState);
        }
        
        public System.DateTime GetServerDate() {
            return base.Channel.GetServerDate();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetServerDate(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetServerDate(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.DateTime EndGetServerDate(System.IAsyncResult result) {
            return base.Channel.EndGetServerDate(result);
        }
        
        private System.IAsyncResult OnBeginGetServerDate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetServerDate(callback, asyncState);
        }
        
        private object[] OnEndGetServerDate(System.IAsyncResult result) {
            System.DateTime retVal = this.EndGetServerDate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetServerDateCompleted(object state) {
            if ((this.GetServerDateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetServerDateCompleted(this, new GetServerDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetServerDateAsync() {
            this.GetServerDateAsync(null);
        }
        
        public void GetServerDateAsync(object userState) {
            if ((this.onBeginGetServerDateDelegate == null)) {
                this.onBeginGetServerDateDelegate = new BeginOperationDelegate(this.OnBeginGetServerDate);
            }
            if ((this.onEndGetServerDateDelegate == null)) {
                this.onEndGetServerDateDelegate = new EndOperationDelegate(this.OnEndGetServerDate);
            }
            if ((this.onGetServerDateCompletedDelegate == null)) {
                this.onGetServerDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetServerDateCompleted);
            }
            base.InvokeAsync(this.onBeginGetServerDateDelegate, null, this.onEndGetServerDateDelegate, this.onGetServerDateCompletedDelegate, userState);
        }
        
        public double MultiplyThreeNumbers(double x1, double x2, double x3) {
            return base.Channel.MultiplyThreeNumbers(x1, x2, x3);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMultiplyThreeNumbers(double x1, double x2, double x3, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMultiplyThreeNumbers(x1, x2, x3, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndMultiplyThreeNumbers(System.IAsyncResult result) {
            return base.Channel.EndMultiplyThreeNumbers(result);
        }
        
        private System.IAsyncResult OnBeginMultiplyThreeNumbers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double x1 = ((double)(inValues[0]));
            double x2 = ((double)(inValues[1]));
            double x3 = ((double)(inValues[2]));
            return this.BeginMultiplyThreeNumbers(x1, x2, x3, callback, asyncState);
        }
        
        private object[] OnEndMultiplyThreeNumbers(System.IAsyncResult result) {
            double retVal = this.EndMultiplyThreeNumbers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMultiplyThreeNumbersCompleted(object state) {
            if ((this.MultiplyThreeNumbersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MultiplyThreeNumbersCompleted(this, new MultiplyThreeNumbersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MultiplyThreeNumbersAsync(double x1, double x2, double x3) {
            this.MultiplyThreeNumbersAsync(x1, x2, x3, null);
        }
        
        public void MultiplyThreeNumbersAsync(double x1, double x2, double x3, object userState) {
            if ((this.onBeginMultiplyThreeNumbersDelegate == null)) {
                this.onBeginMultiplyThreeNumbersDelegate = new BeginOperationDelegate(this.OnBeginMultiplyThreeNumbers);
            }
            if ((this.onEndMultiplyThreeNumbersDelegate == null)) {
                this.onEndMultiplyThreeNumbersDelegate = new EndOperationDelegate(this.OnEndMultiplyThreeNumbers);
            }
            if ((this.onMultiplyThreeNumbersCompletedDelegate == null)) {
                this.onMultiplyThreeNumbersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMultiplyThreeNumbersCompleted);
            }
            base.InvokeAsync(this.onBeginMultiplyThreeNumbersDelegate, new object[] {
                        x1,
                        x2,
                        x3}, this.onEndMultiplyThreeNumbersDelegate, this.onMultiplyThreeNumbersCompletedDelegate, userState);
        }
    }
}
